[theme]
# Primary accent color for interactive elements
primaryColor = "#3366CC"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Enables development features when running a Streamlit script
enableCors = true 
enableXsrfProtection = true

[browser]
gatherUsageStats = false